### ISSUE TITLE
KeyError: 'lag_period'

### ISSUE THREAD

**Issue by volemont** [ScottFreeLLC/AlphaPy#14]
Commands used on OSX:

```
pip install xgboost
pip install -U alphapy
git clone https://github.com/ScottFreeLLC/AlphaPy.git
cd AlphaPy/alphapy/examples/Trading\ Model/
mflow --pdate 2017-01-01
```

Output:
```

/usr/local/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
None
/usr/local/lib/python3.6/site-packages/sklearn/learning_curve.py:22: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the functions are moved. This module will be removed in 0.20
  DeprecationWarning)
[11/22/17 08:53:30] INFO	********************************************************************************
[11/22/17 08:53:30] INFO	MarketFlow Start
[11/22/17 08:53:30] INFO	********************************************************************************
[11/22/17 08:53:30] INFO	Training Date: 1900-01-01
[11/22/17 08:53:30] INFO	Prediction Date: 2017-01-01
[11/22/17 08:53:30] INFO	MarketFlow Configuration
Traceback (most recent call last):
  File "/usr/local/bin/mflow", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/alphapy/market_flow.py", line 363, in main
    market_specs = get_market_config()
  File "/usr/local/lib/python3.6/site-packages/alphapy/market_flow.py", line 94, in get_market_config
    specs['lag_period'] = cfg['market']['lag_period']
KeyError: 'lag_period'
```

**Comment by mrconway** [comment]
Thank you. We have to update some of the examples for the most recent changes.

**Comment by mrconway** [comment]
Fixed in release https://github.com/ScottFreeLLC/AlphaPy/releases/tag/2.2.1

**Comment by mrconway** [comment]
Fixed in release https://github.com/ScottFreeLLC/AlphaPy/releases/tag/2.2.1
