### ISSUE TITLE
How do i run this with nvidia-docker?

### ISSUE THREAD

**Issue by oppsig** [ScottfreeLLC/AlphaPy#24]
This happends when i launch mflow --predict.
```
root@b1efe70104d6:/app# pip freeze | grep tensorflow
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tensorflow-gpu==1.11.0
root@b1efe70104d6:/app# mflow --predict
/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Using TensorFlow backend.
Illegal instruction (core dumped)

```

**Comment by oppsig** [comment]
Ok so i got a bit further. My prosessor is kinda old, it's a qx9850. So i had to downgrade tensorflow-gpu to 1.05 because of avx issue with older processors.

`root@b1efe70104d6:/app/alphapy/examples/Trading Model# mflow --predict
/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Using TensorFlow backend.
None
[11/01/18 17:58:54] INFO	********************************************************************************
[11/01/18 17:58:54] INFO	MarketFlow Start
[11/01/18 17:58:54] INFO	********************************************************************************
[11/01/18 17:58:54] INFO	Training Date: 1900-01-01
[11/01/18 17:58:54] INFO	Prediction Date: 2018-11-01
[11/01/18 17:58:54] INFO	MarketFlow Configuration
Traceback (most recent call last):
  File "/usr/local/bin/mflow", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/alphapy/market_flow.py", line 394, in main
    market_specs = get_market_config()
  File "/usr/local/lib/python2.7/dist-packages/alphapy/market_flow.py", line 106, in get_market_config
    specs['forecast_period'] = cfg['market']['forecast_period']
KeyError: 'forecast_period'
`
