### ISSUE TITLE
Model.yml encoding error

### ISSUE THREAD

**Issue by thegamecat** [ScottfreeLLC/AlphaPy#27]
Running this via Windows WSL (winbash).
Python 3.7

Run mflow and get this error:

Traceback (most recent call last):
  File "/home/d/.local/bin/mflow", line 8, in <module>
    sys.exit(main())
  File "/home/d/.local/lib/python3.7/site-packages/alphapy/market_flow.py", line 412, in main
    model_specs = get_model_config()
  File "/home/d/.local/lib/python3.7/site-packages/alphapy/model.py", line 274, in get_model_config
    raise ValueError("model.yml features:encoding:type %s unrecognized" % encoder)
ValueError: model.yml features:encoding:type factorize unrecognized

This is from the config entry in console:

[03/01/20 01:54:19] INFO        ********************************************************************************
[03/01/20 01:54:19] INFO        MarketFlow Start
[03/01/20 01:54:19] INFO        ********************************************************************************
[03/01/20 01:54:19] INFO        Training Date: 1900-01-01
[03/01/20 01:54:19] INFO        Prediction Date: 2020-03-01
[03/01/20 01:54:19] INFO        MarketFlow Configuration
[03/01/20 01:54:19] INFO        Getting Features
[03/01/20 01:54:19] INFO        No Features Found
[03/01/20 01:54:19] INFO        Defining Groups
[03/01/20 01:54:19] INFO        Added: {'googl', 'fb', 'aapl', 'amzn', 'nflx'}
[03/01/20 01:54:19] INFO        Defining Aliases
[03/01/20 01:54:19] INFO        Getting System Parameters
[03/01/20 01:54:19] INFO        Defining AlphaPy Variables [phigh, plow]
[03/01/20 01:54:19] INFO        Defining User Variables
[03/01/20 01:54:19] INFO        No Variables Found
[03/01/20 01:54:19] INFO        Getting Variable Functions
[03/01/20 01:54:19] INFO        No Variable Functions Found
[03/01/20 01:54:19] INFO        MARKET PARAMETERS:
[03/01/20 01:54:19] INFO        api_key         = None
[03/01/20 01:54:19] INFO        api_key_name    = None
[03/01/20 01:54:19] INFO        create_model    = False
[03/01/20 01:54:19] INFO        data_fractal    = 1d
[03/01/20 01:54:19] INFO        data_history    = 500
[03/01/20 01:54:19] INFO        features        = {}
[03/01/20 01:54:19] INFO        forecast_period = 1
[03/01/20 01:54:19] INFO        fractal         = 1d
[03/01/20 01:54:19] INFO        lag_period      = 1
[03/01/20 01:54:19] INFO        leaders         = []
[03/01/20 01:54:19] INFO        predict_history = 50
[03/01/20 01:54:19] INFO        schema          = yahoo
[03/01/20 01:54:19] INFO        subject         = stock
[03/01/20 01:54:19] INFO        subschema       = None
[03/01/20 01:54:19] INFO        system          = {'name': 'closer', 'holdperiod': 0, 'longentry': 'hc', 'longexit': None, 'shortentry': 'lc', 'shortexit': None, 'scale': False}

**Comment by mrconway** [comment]
Yes, 'factorize' is no longer a supported encoding. Just change this section of the model.yml file:

    encoding          :
        rounding      : 3
        type          : target

We'll update the examples accordingly.

Thank you!

**Comment by thegamecat** [comment]
Perfect that works.

**Comment by mrconway** [comment]
Examples fixed in 2.4.1
