### ISSUE TITLE
AttributeError: type object 'DataFrame' has no attribute 'from_items'

### ISSUE THREAD

**Issue by thegamecat** [ScottfreeLLC/AlphaPy#28]
Winbash python3.7 running mflow:

Traceback (most recent call last):
  File "/home/freefall/.local/bin/mflow", line 8, in <module>
    sys.exit(main())
  File "/home/d/.local/lib/python3.7/site-packages/alphapy/market_flow.py", line 430, in main
    model = market_pipeline(model, market_specs)
  File "/home/d/.local/lib/python3.7/site-packages/alphapy/market_flow.py", line 318, in market_pipeline
    tfs = run_system(model, system, group, intraday)
  File "/home/fredefall/.local/lib/python3.7/site-packages/alphapy/system.py", line 370, in run_system
    tf = DataFrame.from_items(gtlist, orient='index', columns=Trade.states)
AttributeError: type object 'DataFrame' has no attribute 'from_items'

**Comment by mrconway** [comment]
Yes, DataFrame.from_items was deprecated in pandas 1.0. We'll put in a fix for this shortly.

**Comment by mrconway** [comment]
Fixed in 2.4.1
