### ISSUE TITLE
ValueError: max() arg is an empty sequence and NameError: name 'search_path' is not defined

### ISSUE THREAD

**Issue by maxpolokov** [ScottfreeLLC/AlphaPy#29]
Running python 3.7.6 on command line, NCAAB tutorial on Alphapy 2.4.1

[03/10/20 17:05:51] INFO        Running Model
[03/10/20 17:05:51] INFO        Predict Mode
[03/10/20 17:05:51] INFO        Loading Data
[03/10/20 17:05:51] INFO        Loading data from ./input/train.csv
[03/10/20 17:05:51] INFO        Could not find or access ./input/train.csv
[03/10/20 17:05:51] INFO        Loading Data
[03/10/20 17:05:51] INFO        Loading data from ./input/predict.csv
[03/10/20 17:05:51] INFO        Found target won_on_spread in data frame
[03/10/20 17:05:51] INFO        Labels (y) found for Partition.predict
Traceback (most recent call last):
  File "c:\users\home\anaconda3\lib\site-packages\alphapy\model.py", line 576, in load_feature_map
    file_name = most_recent_file(search_dir, 'feature_map_*.pkl')
  File "c:\users\home\anaconda3\lib\site-packages\alphapy\utilities.py", line 93, in most_recent_file
    file_name = max(glob.iglob(search_path), key=os.path.getctime)
ValueError: max() arg is an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\home\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\home\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\home\Anaconda3\Scripts\sflow.exe\__main__.py", line 7, in <module>
  File "c:\users\home\anaconda3\lib\site-packages\alphapy\sport_flow.py", line 909, in main
    model = main_pipeline(model)
  File "c:\users\home\anaconda3\lib\site-packages\alphapy\__main__.py", line 424, in main_pipeline
    model = prediction_pipeline(model)
  File "c:\users\home\anaconda3\lib\site-packages\alphapy\__main__.py", line 336, in prediction_pipeline
    model = load_feature_map(model, directory)
  File "c:\users\home\anaconda3\lib\site-packages\alphapy\model.py", line 582, in load_feature_map
    logging.error("Could not find feature map in %s", search_path)
NameError: name 'search_path' is not defined

**Comment by mrconway** [comment]
Fixed in 2.4.2
